source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'sehkaiSwiftExtension_Example' do
  pod "SKSwiftExtension", :path => "../"
end

target 'sehkaiSwiftExtension_Tests' do
  pod "SKSwiftExtension", :path => "../"

  pod 'Quick'
  pod 'Nimble'
  # pod 'FBSnapshotTestCase'
  # pod 'Nimble-Snapshots'
end
