source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'sehkaiSwiftExtension_Example', :exclusive => true do
  pod "SKSwiftExtension", :path => "../"
end

target 'sehkaiSwiftExtension_Tests', :exclusive => true do
  pod "SKSwiftExtension", :path => "../"

  pod 'Quick', '~> 0.9.0'
  pod 'Nimble'
end
